name: 'Extract Trailers'
description: 'Parse trailers of a message and make them available to the workflow'
inputs:
  message:
    description: 'Message to parse'
    required: true
outputs:
  trailers:
    description: 'The trailers'
runs:
  using: 'node12'
  main: 'dist/index.js'
